import subprocess
import argparse
import os
import shutil

"""
Simple script for running Imagemagick on source images to convert them to 1 bit images for Playdate
"""
CHAR_W = 48
CHAR_H = 48
ENV_W = 64
ENV_H = 88

"""
Run imagemagick on all the files in the given folder
"""
def convertCharacterSprites(imagemagick, dir_name):
    for f in os.listdir(dir_name):
        input_path = os.path.join(dir_name, f)
        output_path = os.path.join('images', f)
        cmds = [imagemagick, input_path, "-transparent", "red", "-background", "none", "-colorspace", "gray", "-ordered-dither", "h6x6a", "-gravity", "center", "-extent", "648x648", "-resize", f"{CHAR_W}x{CHAR_H}", output_path]
        p = subprocess.Popen(cmds, stdout=subprocess.PIPE, shell=True)
        p.communicate()

"""
Run imagemagick on all the files in the given folder
"""
def convertEnvironmentSprites(imagemagick, dir_name):
    for f in os.listdir(dir_name):
        input_path = os.path.join(dir_name, f)
        output_path = os.path.join('images', f)
        # cmds = [imagemagick, input_path, "-colorspace", "gray", "-ordered-dither", "o2x2", "-resize", "64x88", output_path]
        cmds = [imagemagick, input_path, "-posterize", "2", "-colorspace", "gray", "-resize", f"{ENV_W}x{ENV_H}", output_path]
        p = subprocess.Popen(cmds, stdout=subprocess.PIPE, shell=True)
        p.communicate()

"""
Write a zig file with the dimensions
"""
def createDescFile():
    with open("src/bitmap_descs.zig", 'w') as f:
        f.write("//Autogenerated\n")
        f.write(f"pub const CHAR_W: u32 = {CHAR_W};\n")
        f.write(f"pub const CHAR_H: u32 = {CHAR_H};\n")
        f.write(f"pub const ENV_OBJ_W: u32 = {ENV_W};\n")
        f.write(f"pub const ENV_OBJ_H: u32 = {ENV_H};\n")
        f.close();


if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog = 'Convert Raw Images', description = 'Convert pngs to 1bit images for Playdate')
    parser.add_argument('imagemagick') 

    args = parser.parse_args() 

    if os.path.isdir('images'):
        shutil.rmtree('images')
    os.mkdir('images')

    # Characters
    convertCharacterSprites(args.imagemagick, "raw-images\\Hero1")
    convertCharacterSprites(args.imagemagick, "raw-images\\Enemy1")

    # Environment
    convertEnvironmentSprites(args.imagemagick, "raw-levels")

    # BGs
    cmds = [args.imagemagick, "raw-images\\bg.png", "-colorspace", "gray", "-ordered-dither", "h4x4a", "images\\bg.png"]
    p = subprocess.Popen(cmds, stdout=subprocess.PIPE, shell=True)
    p.communicate()

    # Launchers
    cmds = [args.imagemagick, "raw-images\\card.png", "-colorspace", "gray", "images\\card.png"]
    p = subprocess.Popen(cmds, stdout=subprocess.PIPE, shell=True)
    p.communicate()

    createDescFile()
